esphome:
  platform: ESP8266
  board: esp12e
  esp8266_restore_from_flash: true

packages:
  core:
    ref: main
    url: https://github.com/alexyao2015/ESPHomeYAML
    files:
      - yaml/switches/core/core.yaml
  sprinkler:
    ref: main
    url: https://github.com/alexyao2015/ESPHomeYAML
    files:
      # - yaml/switches/sprinkler/buttons.yaml
      - yaml/switches/sprinkler/display.yaml
      - yaml/switches/sprinkler/led.yaml
      - yaml/switches/sprinkler/relay.yaml
