esphome:
  platform: ESP8266
  board: esp12e

packages:
  # buttons: !include buttons.yaml
  core: !include ../core/core.yaml
  display: !include display.yaml
  led: !include led.yaml
  relay: !include relay.yaml
