esphome:
  platform: ESP8266
  board: esp12e

packages:
  core:
    refresh: 0s
    ref: remote-packages
    url: https://github.com/alexyao2015/ESPHomeYAML
    files:
      - yaml/switches/core/core.yaml
  sprinkler:
    refresh: 0s
    ref: remote-packages
    url: https://github.com/alexyao2015/ESPHomeYAML
    files:
      # - yaml/switches/sprinkler/buttons.yaml
      - yaml/switches/sprinkler/display.yaml
      - yaml/switches/sprinkler/led.yaml
      - yaml/switches/sprinkler/relay.yaml
