esphome:
  platform: ESP8266
  board: esp01_1m
  esp8266_restore_from_flash: true

packages:
  core:
    ref: remote-packages
    url: https://github.com/alexyao2015/ESPHomeYAML
    files:
      - yaml/switches/core/core.yaml
  intertek-plug:
    ref: remote-packages
    url: https://github.com/alexyao2015/ESPHomeYAML
    files:
      - yaml/switches/esicoo-plug/buttons.yaml
      - yaml/switches/esicoo-plug/led.yaml
      - yaml/switches/esicoo-plug/relay.yaml
