i2c:
  sda: 4
  scl: 5
  scan: True

sensor:
  - platform: bme680
    temperature:
      name: "Temperature"
      id: temperature_sensor
      oversampling: 16x
    pressure:
      name: "Pressure"
    humidity:
      name: "Humidity"
    gas_resistance:
      name: "Gas Resistance"
    address: 0x77
    update_interval: 3s
