esphome:
  platform: ESP32
  board: node32s

logger:
  baud_rate: 0

packages:
  core:
    ref: main
    url: https://github.com/alexyao2015/ESPHomeYAML
    files:
      - yaml/sensors/core/core.yaml
  serial-bridge:
    ref: main
    url: https://github.com/alexyao2015/ESPHomeYAML
    files:
      - yaml/sensors/serial-bridge/bridge.yaml
      - yaml/sensors/serial-bridge/led.yaml
