esphome:
  platform: ESP8266
  board: esp01_1m

packages:
  core:
    refresh: 0s
    ref: remote-packages
    url: https://github.com/alexyao2015/ESPHomeYAML
    files:
      - yaml/switches/core/core.yaml
  sonoff:
    refresh: 0s
    ref: remote-packages
    url: https://github.com/alexyao2015/ESPHomeYAML
    files:
      - yaml/switches/sonoff/buttons.yaml
      - yaml/switches/sonoff/led.yaml
      - yaml/switches/sonoff/relay.yaml
