esphome:
  platform: ESP8266
  board: esp12e

packages:
  core:
    refresh: 0s
    ref: remote-packages
    url: https://github.com/alexyao2015/ESPHomeYAML
    files:
      - yaml/sensors/core/core.yaml
  temp-sensor:
    refresh: 0s
    ref: remote-packages
    url: https://github.com/alexyao2015/ESPHomeYAML
    files:
      - yaml/sensors/temp-sensor/led.yaml
      - yaml/sensors/temp-sensor/sensor.yaml
