substitutions:
  devicename: device_name_without_spaces
  real_devicename: Im a cool device

wifi:
  manual_ip:
    static_ip: 192.168.1.1
    gateway: 192.168.1.1
    subnet: 255.255.255.0

packages:
  diyhue: !include yaml/lights/diyhue/core.yaml
  device_model: !include yaml/lights/feit/core.yaml
  lifx: !include yaml/lights/lifxemulation/core.yaml
  wifi: !include yaml/wifi.yaml

custom_component:
  - lambda: |-
      auto LifxLAN = new lifxUdp();
      LifxLAN->set_bulbLabel( App.get_name().c_str() );
      WiFi.macAddress(LifxLAN->mac);
      
      LifxLAN->bulbLocationTime = 1600530356000000000;
      LifxLAN->set_bulbLocation( "My Home" );
      LifxLAN->set_bulbLocationGUID( "c019266d-0535-4b57-86ef-aca609ee9915" );
      LifxLAN->bulbGroupTime = 1600358586632000000;
      LifxLAN->set_bulbGroup( "Outside" );
      LifxLAN->set_bulbGroupGUID( "59d16606-0a70-4ba8-8d98-45521a6e1669" );
      LifxLAN->beginUDP();
      return {LifxLAN};
