# Requires custom component from 
# https://github.com/hass-emulated-hue/esphome-components
# to operate

substitutions:
  devicename: device_name_without_spaces
  real_devicename: Im a cool device

wifi:
  manual_ip:
    static_ip: 192.168.1.1
    gateway: 192.168.1.1
    subnet: 255.255.255.0

packages:
  device_model: !include yaml/lights/feit_sm16716/core.yaml
  wifi: !include yaml/wifi.yaml
