esphome:
  name: ${devicename}
  flash_write_interval: 1min

ota:
  password: !secret otapassword

api:
  password: !secret apipassword

time:
  - platform: homeassistant
    id: homeassistant_time

logger:
  # baud_rate: 0

switch:
  - platform: restart
    id: restart_switch

web_server:
  port: 80

packages:
  globals: !include globals.yaml
  scripts: !include scripts.yaml
