esphome:
  platform: ESP32
  board: node32s

packages:
  core:
    refresh: 0s
    ref: remote-packages
    url: https://github.com/alexyao2015/ESPHomeYAML
    files:
      - yaml/switches/core/core.yaml
  sprinkler32:
    refresh: 0s
    ref: remote-packages
    url: https://github.com/alexyao2015/ESPHomeYAML
    files:
      # - yaml/switches/sprinkler/buttons.yaml
      - yaml/switches/sprinkler32/display.yaml
      - yaml/switches/sprinkler32/led.yaml
      - yaml/switches/sprinkler32/relay.yaml
