binary_sensor:
  - platform: gpio
    pin:
      number: GPIO1
      mode: INPUT_PULLUP
      inverted: True
    id: button
    on_click:
      - min_length: 50ms
        max_length: 750ms
        then:
          - switch.toggle: template_relay_1
      - min_length: 3000ms
        max_length: 6000ms
        then:
          - switch.turn_on: "${devicename}_restart"