esphome:
  name: ${devicename}
  friendly_name: ${real_devicename}
preferences: #<< in 2021.10 release
  flash_write_interval: 1min

ota:
  password: !secret ota-password

api:
  password: !secret api-password
  # encryption:
  #   key: !secret api-encryption-key

time:
  - platform: homeassistant
    id: homeassistant_time

logger:

switch:
  - platform: restart
    id: restart_switch

web_server:
  port: 80
  auth:
    username: !secret web-user
    password: !secret web-password

wifi:
  ssid: !secret ssid
  password: !secret ssid-password
  ap:
    ssid: "ESPHome ${real_devicename}"
    password: !secret ap-password
  domain: !secret wifi-domain

sensor:
  - platform: wifi_signal
    name: "${real_devicename} WiFi Signal"
    update_interval: 60s

text_sensor:
  - platform: wifi_info
    ip_address:
      name: "${real_devicename} IP Address"
  - platform: version
    name: "${real_devicename} ESPHome Version"

captive_portal:
