esphome:
  name: ${devicename}
  friendly_name: ${real_devicename}
preferences: #<< in 2021.10 release
  flash_write_interval: 1min

ota:
  - platform: esphome
    password: !secret ota-password

api:
  id: api_apiserver_id
  # password: !secret api-password
  # encryption:
  #   key: !secret api-encryption-key

time:
  - platform: homeassistant
    id: homeassistant_time

logger:

switch:
  - platform: restart
    id: restart_switch

web_server:
  port: 80
  auth:
    username: !secret web-user
    password: !secret web-password

button:
  - platform: restart
    id: restart_button
    name: "Restart ESPHome Node"
    disabled_by_default: true

text_sensor:
  - platform: version
    id: esphome_version
    name: "ESPHome Version"
    disabled_by_default: true

sensor:
  - platform: uptime
    id: uptime_sensor
    name: "Uptime"
    disabled_by_default: true

binary_sensor:
  - platform: status
    id: status_sensor
    name: "API Connection"
    disabled_by_default: true
