esphome:
  platform: ESP8266
  board: esp01_1m
  esp8266_restore_from_flash: true

packages:
  core: !include ../core/core.yaml
  buttons: !include buttons.yaml
  led: !include led.yaml
  relay: !include relay.yaml
