esphome:
  platform: ESP8266
  board: esp01_1m

packages:
  core:
    refresh: 0s
    ref: remote-packages
    url: https://github.com/alexyao2015/ESPHomeYAML
    files:
      - yaml/switches/core/core.yaml
  kuled-switch:
    refresh: 0s
    ref: remote-packages
    url: https://github.com/alexyao2015/ESPHomeYAML
    files:
      - yaml/switches/kuled-switch/buttons.yaml
      - yaml/switches/kuled-switch/led.yaml
      - yaml/switches/kuled-switch/relay.yaml
