esphome:
  name: ${devicename}
  flash_write_interval: 1min

ota:
  password: !secret otapassword

api:
  password: !secret apipassword
  reboot_timeout: 0s

wifi:
  reboot_timeout: 0s

logger:
  baud_rate: 0
    
web_server:
  port: 80
