substitutions:
  devicename: ir-bridge-2
  real_devicename: IR Bridge 2
  button_inverted: "true"
  button_gpio: GPIO13
  led_inverted: "false"
  led_gpio: GPIO4
  ir_receiver_gpio: GPIO05
  ir_receiver_inverted: "true"
  ir_transmitter_gpio: GPIO14
  ir_transmitter_inverted: "false"

packages:
  device:
    refresh: 0s
    ref: remote-packages
    url: https://github.com/alexyao2015/ESPHomeYAML
    files:
      - yaml/sensors/tuya-ir-bridge/core.yaml

script:
  - id: on_gicable
    mode: queued
    then:
      - lambda: |-
          return;

  - id: on_xmp
    mode: queued
    then:
      - lambda: |-
          return;

  - id: on_raw
    mode: queued
    then:
      - homeassistant.event:
          event: esphome.ir-bridge-2-raw-received
          data_template:
            title: !lambda |-
              std::string result = "[";
              auto it = id(raw_data).begin();
              result = result + to_string(*it++);
              for (; it != id(raw_data).end(); it++) {
                  result = result + "," + to_string(*it);
              }
              result = result + "]";
              return result;
