substitutions:
  devicename: ir-bridge-2
  real_devicename: IR Bridge 2

packages:
  device:
    refresh: 0s
    ref: remote-packages
    url: https://github.com/alexyao2015/ESPHomeYAML
    files:
      - yaml/sensors/tuya-ir-bridge/core.yaml
      
output:
  - platform: esp8266_pwm
    id: basic_led
    pin: GPIO4
