substitutions:
  # basement closet
  devicename: ir-bridge-1
  real_devicename: IR Bridge 1
  button_inverted: "true"
  button_gpio: GPIO13
  led_inverted: "true"
  led_gpio: GPIO4
  ir_receiver_gpio: GPIO05
  ir_receiver_inverted: "true"
  ir_transmitter_gpio: GPIO14
  ir_transmitter_inverted: "false"

packages:
  device:
    refresh: 0s
    ref: main
    url: https://github.com/alexyao2015/ESPHomeYAML
    files:
      - yaml/sensors/tuya-ir-bridge/core.yaml

button:
  - platform: template
    name: "${devicename}_Xiaomi Home"
    id: xiaomi_home
    on_press:
      then:
        - remote_transmitter.transmit_raw:
            carrier_frequency: 36kHz
            code: [1000,-580,580,-1160,580,-580,580,-870,580,-1160,580,-580,580,-580,580,-1160,580,-580,580,-870,580,-1160,580,-12180]

  - platform: template
    name: "${devicename}_Xiaomi Back"
    id: xiaomi_back
    on_press:
      then:
        - remote_transmitter.transmit_raw:
            carrier_frequency: 36kHz
            code: [1000,-580,580,-1160,580,-580,580,-870,580,-1160,580,-580,580,-580,580,-870,580,-1450,580,-1160,580,-870,580,-12180]

  - platform: template
    name: "${devicename}_Xiaomi Up"
    id: xiaomi_up
    on_press:
      then:
        - remote_transmitter.transmit_raw:
            carrier_frequency: 36kHz
            code: [1000,-580,580,-1160,580,-580,580,-870,580,-1160,580,-580,580,-580,580,-870,580,-870,580,-1160,580,-1450,580,-12180]

  - platform: template
    name: "${devicename}_Xiaomi Left"
    id: xiaomi_left
    on_press:
      then:
        - remote_transmitter.transmit_raw:
            carrier_frequency: 36kHz
            code: [1000,-580,580,-1160,580,-580,580,-870,580,-1160,580,-580,580,-580,580,-1160,580,-1450,580,-870,580,-870,580,-12180]

  - platform: template
    name: "${devicename}_Xiaomi Right"
    id: xiaomi_right
    on_press:
      then:
        - remote_transmitter.transmit_raw:
            carrier_frequency: 36kHz
            code: [1000,-580,580,-1160,580,-580,580,-870,580,-1160,580,-580,580,-580,580,-1450,580,-580,580,-580,580,-1160,580,-12180]

  - platform: template
    name: "${devicename}_Xiaomi Down"
    id: xiaomi_down
    on_press:
      then:
        - remote_transmitter.transmit_raw:
            carrier_frequency: 36kHz
            code: [1000,-580,580,-1160,580,-580,580,-870,580,-1160,580,-580,580,-580,580,-870,580,-1160,580,-1160,580,-580,580,-12180]

  - platform: template
    name: "${devicename}_Xiaomi Ok"
    id: xiaomi_ok
    on_press:
      then:
        - remote_transmitter.transmit_raw:
            carrier_frequency: 36kHz
            code: [1000,-580,580,-1160,580,-580,580,-870,580,-1160,580,-580,580,-580,580,-1450,580,-870,580,-580,580,-1450,580,-12180]

  - platform: template
    name: "${devicename}_Xiaomi Vol Up"
    id: xiaomi_vol_up
    on_press:
      then:
        - remote_transmitter.transmit_raw:
            carrier_frequency: 36kHz
            code: [1000,-580,580,-1160,580,-580,580,-870,580,-1160,580,-580,580,-580,580,-1450,580,-1160,580,-580,580,-580,580,-12180,1000,-580,580,-1160,580,-580,580,-870,580,-1160,580,-580,580,-580,580,-1450,580,-1160,580,-580,580,-580,580,-12180]

  - platform: template
    name: "${devicename}_Xiaomi Vol Down"
    id: xiaomi_vol_down
    on_press:
      then:
        - remote_transmitter.transmit_raw:
            carrier_frequency: 36kHz
            code: [1000,-580,580,-1160,580,-580,580,-870,580,-1160,580,-580,580,-580,580,-1450,580,-1450,580,-580,580,-870,580,-12180,1000,-580,580,-1160,580,-580,580,-870,580,-1160,580,-580,580,-580,580,-1450,580,-1450,580,-580,580,-870,580,-12180]

binary_sensor:
  - platform: remote_receiver
    name: "${devicename}_XMP Guide Button -> Xiaomi Home"
    xmp:
      address: 0x170F443E
      command: 0x16002700
    on_press:
      then:
        - button.press: xiaomi_home

  - platform: remote_receiver
    name: "${devicename}_XMP Last -> Xiaomi Back"
    xmp:
      address: 0x170F443E
      command: 0x19005100
    on_press:
      then:
        - button.press: xiaomi_back

  - platform: remote_receiver
    name: "${devicename}_XMP UP Repeat -> Xiaomi UP"
    xmp:
      address: 0x170F443E
      command: 0x14802100
    on_press:
      then:
        - button.press: xiaomi_up

  - platform: remote_receiver
    name: "${devicename}_XMP Left Repeat -> Xiaomi Left"
    xmp:
      address: 0x170F443E
      command: 0x12802300
    on_press:
      then:
        - button.press: xiaomi_left

  - platform: remote_receiver
    name: "${devicename}_XMP Right Repeat -> Xiaomi Right"
    xmp:
      address: 0x170F443E
      command: 0x11802400
    on_press:
      then:
        - button.press: xiaomi_right

  - platform: remote_receiver
    name: "${devicename}_XMP Down Repeat -> Xiaomi Down"
    xmp:
      address: 0x170F443E
      command: 0x13802200
    on_press:
      then:
        - button.press: xiaomi_down

  - platform: remote_receiver
    name: "${devicename}_XMP Select -> Xiaomi Ok"
    xmp:
      address: 0x170F443E
      command: 0x18002500
    on_press:
      then:
        - button.press: xiaomi_ok

  - platform: remote_receiver
    name: "${devicename}_NEC2 Vol Up Repeat -> Xiaomi Vol UP"
    nec2:
      address: 0x20DF
      command: 0x40BF
      repeat: true
    on_press:
      then:
        - button.press: xiaomi_vol_up

  - platform: remote_receiver
    name: "${devicename}_NEC2 Vol Down Repeat -> Xiaomi Vol Down"
    nec2:
      address: 0x20DF
      command: 0xC03F
      repeat: true
    on_press:
      then:
        - button.press: xiaomi_vol_down

script:
  - id: on_gicable
    then:
      - homeassistant.event:
          event: esphome.${devicename}-gicable-received
          data:
            code: !lambda |-
              char formatted[100];
              sprintf(formatted, "Received GiCable: command=0x%04X, repeat=%d", id(gicable_data).command, id(gicable_data).repeat);
              return std::string(formatted);
  - id: on_xmp
    then:
      - homeassistant.event:
          event: esphome.${devicename}-xmp-received
          data:
            code: !lambda |-
              char formatted[100];
              sprintf(formatted, "Received XMP: address=0x%08X, command=0x%08X", id(xmp_data).address, id(xmp_data).command);
              return std::string(formatted);
  - id: on_raw
    then:
      - homeassistant.event:
          event: esphome.${devicename}-raw-received
          data_template:
            code: !lambda |-
              char buf[20];
              std::string res;
              res += "[";
              size_t len = id(raw_data).size();
              for (int i = 0; i < len; i++) {
                if (i + 1 != len) {
                  sprintf(buf, "%d,", id(raw_data).at(i));
                } else {
                  sprintf(buf, "%d ", id(raw_data).at(i));
                }
                res += buf;
              }
              res += "]";
              return res;