substitutions:
  devicename: ir-bridge-2
  real_devicename: IR Bridge 2
  button_inverted: true
  button_gpio: GPIO4
  led_inverted: false
  led_gpio: GPIO4
  ir_receiver_gpio: GPIO05
  ir_receiver_inverted: true
  ir_transmitter_gpio: GPIO14
  ir_transmitter_inverted: false

packages:
  device:
    refresh: 0s
    ref: remote-packages
    url: https://github.com/alexyao2015/ESPHomeYAML
    files:
      - yaml/sensors/tuya-ir-bridge/core.yaml
      
output:
  - platform: esp8266_pwm
    id: basic_led
    pin: GPIO4
