substitutions:
  devicename: ir-bridge-1
  real_devicename: IR Bridge 1
  button_inverted: "true"
  button_gpio: GPIO13
  led_inverted: "true"
  led_gpio: GPIO4
  ir_receiver_gpio: GPIO05
  ir_receiver_inverted: "true"
  ir_transmitter_gpio: GPIO14
  ir_transmitter_inverted: "false"

packages:
  device:
    refresh: 0s
    ref: remote-packages
    url: https://github.com/alexyao2015/ESPHomeYAML
    files:
      - yaml/sensors/tuya-ir-bridge/core.yaml

output:
  - platform: esp8266_pwm
    id: basic_led
    inverted: True
    pin: GPIO4

switch:
  - platform: template
    name: "Xiaomi Home"
    id: xiaomi_home
    optimistic: false
    restore_state: false
    turn_on_action:
      then:
        - remote_transmitter.transmit_raw:
            carrier_frequency: 36kHz
            code: [1000,-580,580,-1160,580,-580,580,-870,580,-1160,580,-580,580,-580,580,-1160,580,-580,580,-870,580,-1160,580,-12180]
        - switch.turn_off: xiaomi_home

  - platform: template
    name: "Xiaomi Back"
    id: xiaomi_back
    optimistic: false
    restore_state: false
    turn_on_action:
      then:
        - remote_transmitter.transmit_raw:
            carrier_frequency: 36kHz
            code: [1000,-580,580,-1160,580,-580,580,-870,580,-1160,580,-580,580,-580,580,-870,580,-1450,580,-1160,580,-870,580,-12180]
        - switch.turn_off: xiaomi_back

  - platform: template
    name: "Xiaomi Up"
    id: xiaomi_up
    optimistic: false
    restore_state: false
    turn_on_action:
      then:
        - remote_transmitter.transmit_raw:
            carrier_frequency: 36kHz
            code: [1000,-580,580,-1160,580,-580,580,-870,580,-1160,580,-580,580,-580,580,-870,580,-870,580,-1160,580,-1450,580,-12180]
        - switch.turn_off: xiaomi_up

  - platform: template
    name: "Xiaomi Left"
    id: xiaomi_left
    optimistic: false
    restore_state: false
    turn_on_action:
      then:
        - remote_transmitter.transmit_raw:
            carrier_frequency: 36kHz
            code: [1000,-580,580,-1160,580,-580,580,-870,580,-1160,580,-580,580,-580,580,-1160,580,-1450,580,-870,580,-870,580,-12180]
        - switch.turn_off: xiaomi_back

  - platform: template
    name: "Xiaomi Right"
    id: xiaomi_right
    optimistic: false
    restore_state: false
    turn_on_action:
      then:
        - remote_transmitter.transmit_raw:
            carrier_frequency: 36kHz
            code: [1000,-580,580,-1160,580,-580,580,-870,580,-1160,580,-580,580,-580,580,-1450,580,-580,580,-580,580,-1160,580,-12180]
        - switch.turn_off: xiaomi_back

  - platform: template
    name: "Xiaomi Down"
    id: xiaomi_down
    optimistic: false
    restore_state: false
    turn_on_action:
      then:
        - remote_transmitter.transmit_raw:
            carrier_frequency: 36kHz
            code: [1000,-580,580,-1160,580,-580,580,-870,580,-1160,580,-580,580,-580,580,-870,580,-1160,580,-1160,580,-580,580,-12180]
        - switch.turn_off: xiaomi_down

  - platform: template
    name: "Xiaomi Ok"
    id: xiaomi_ok
    optimistic: false
    restore_state: false
    turn_on_action:
      then:
        - remote_transmitter.transmit_raw:
            carrier_frequency: 36kHz
            code: [1000,-580,580,-1160,580,-580,580,-870,580,-1160,580,-580,580,-580,580,-1450,580,-870,580,-580,580,-1450,580,-12180]
        - switch.turn_off: xiaomi_ok

  - platform: template
    name: "Xiaomi Vol Up"
    id: xiaomi_vol_up
    optimistic: false
    restore_state: false
    turn_on_action:
      then:
        - remote_transmitter.transmit_raw:
            carrier_frequency: 36kHz
            code: [1000,-580,580,-1160,580,-580,580,-870,580,-1160,580,-580,580,-580,580,-1450,580,-1160,580,-580,580,-580,580,-12180,1000,-580,580,-1160,580,-580,580,-870,580,-1160,580,-580,580,-580,580,-1450,580,-1160,580,-580,580,-580,580,-12180]
        - switch.turn_off: xiaomi_back

  - platform: template
    name: "Xiaomi Vol Down"
    id: xiaomi_vol_down
    optimistic: false
    restore_state: false
    turn_on_action:
      then:
        - remote_transmitter.transmit_raw:
            carrier_frequency: 36kHz
            code: [1000,-580,580,-1160,580,-580,580,-870,580,-1160,580,-580,580,-580,580,-1450,580,-1450,580,-580,580,-870,580,-12180,1000,-580,580,-1160,580,-580,580,-870,580,-1160,580,-580,580,-580,580,-1450,580,-1450,580,-580,580,-870,580,-12180]
        - switch.turn_off: xiaomi_vol_down

binary_sensor:
  - platform: remote_receiver
    name: "XMP Guide Button -> Xiaomi Home"
    xmp:
      address: 0x170F443E
      command: 0x16002700
    on_press:
      then:
        - switch.turn_on: xiaomi_home

  - platform: remote_receiver
    name: "XMP Last -> Xiaomi Back"
    xmp:
      address: 0x170F443E
      command: 0x19005100
    on_press:
      then:
        - switch.turn_on: xiaomi_back

  - platform: remote_receiver
    name: "XMP UP Repeat -> Xiaomi UP"
    xmp:
      address: 0x170F443E
      command: 0x14802100
    on_press:
      then:
        - switch.turn_on: xiaomi_up

  - platform: remote_receiver
    name: "XMP Left Repeat -> Xiaomi Left"
    xmp:
      address: 0x170F443E
      command: 0x12802300
    on_press:
      then:
        - switch.turn_on: xiaomi_left

  - platform: remote_receiver
    name: "XMP Right Repeat -> Xiaomi Right"
    xmp:
      address: 0x170F443E
      command: 0x11802400
    on_press:
      then:
        - switch.turn_on: xiaomi_right

  - platform: remote_receiver
    name: "XMP Down Repeat -> Xiaomi Down"
    xmp:
      address: 0x170F443E
      command: 0x13802200
    on_press:
      then:
        - switch.turn_on: xiaomi_down

  - platform: remote_receiver
    name: "XMP Select -> Xiaomi Ok"
    xmp:
      address: 0x170F443E
      command: 0x18002500
    on_press:
      then:
        - switch.turn_on: xiaomi_ok

  - platform: remote_receiver
    name: "NEC2 Vol Up Repeat -> Xiaomi Vol UP"
    nec2:
      address: 0x20DF
      command: 0x40BF
      repeat: true
    on_press:
      then:
        - switch.turn_on: xiaomi_vol_up

  - platform: remote_receiver
    name: "NEC2 Vol Down Repeat -> Xiaomi Vol Down"
    nec2:
      address: 0x20DF
      command: 0xC03F
      repeat: true
    on_press:
      then:
        - switch.turn_on: xiaomi_vol_down
