binary_sensor:
  - platform: gpio
    pin:
      number: ${button_gpio}
      mode: INPUT_PULLUP
      inverted: ${button_inverted}
    id: button
    on_click:
      # - min_length: 50ms
      #   max_length: 750ms
      #   then:
      #     - switch.toggle: template_relay_1
      - min_length: 3000ms
        max_length: 6000ms
        then:
          - switch.turn_on: restart_switch