esphome:
  platform: ESP8266
  board: esp01_1m

packages:
  core:
    refresh: 0s
    ref: remote-packages
    url: https://github.com/alexyao2015/ESPHomeYAML
    files:
      - yaml/sensors/core/core.yaml
  tuya-ir-bridge:
    refresh: 0s
    ref: remote-packages
    url: https://github.com/alexyao2015/ESPHomeYAML
    files:
      - yaml/sensors/tuya-ir-bridge/buttons.yaml
      - yaml/sensors/tuya-ir-bridge/led.yaml
      - yaml/sensors/tuya-ir-bridge/remote.yaml
      - yaml/sensors/tuya-ir-bridge/switches.yaml
