api:
  services:
    - service: raw_command
      variables:
        code: int[]
        frequency: int
      then:
        - remote_transmitter.transmit_raw:
            code: !lambda 'return code;'
            carrier_frequency: !lambda 'return frequency;'

switch:
  - platform: template
    name: "Xiaomi Home"
    id: xiaomi_home
    optimistic: false
    restore_state: false
    turn_on_action:
      then:
        - remote_transmitter.transmit_raw:
            carrier_frequency: 36kHz
            code: [1000,-580,580,-1160,580,-580,580,-870,580,-1160,580,-580,580,-580,580,-1160,580,-580,580,-870,580,-1160,580,-12180]
        - switch.turn_off: xiaomi_home

binary_sensor:
  - platform: remote_receiver
    name: "XMP Guide Button -> Xiaomi Home"
    xmp:
      address: 0x170F443E
      command: 0x16002700
    on_press:
      then:
        - switch.turn_on: xiaomi_home

  - platform: remote_receiver
    name: "XMP Last -> Xiaomi Back"
    xmp:
      address: 0x170F443E
      command: 0x19005100
    on_press:
      then:
        - remote_transmitter.transmit_raw:
            carrier_frequency: 36kHz
            code: [1000,-580,580,-1160,580,-580,580,-870,580,-1160,580,-580,580,-580,580,-870,580,-1450,580,-1160,580,-870,580,-12180]

  - platform: remote_receiver
    name: "XMP UP -> Xiaomi UP"
    xmp:
      address: 0x170F443E
      command: 0x1C002100
    on_press:
      then:
        - remote_transmitter.transmit_raw:
            carrier_frequency: 36kHz
            code: [1000,-580,580,-1160,580,-580,580,-870,580,-1160,580,-580,580,-580,580,-870,580,-870,580,-1160,580,-1450,580,-12180]

  - platform: remote_receiver
    name: "XMP Left -> Xiaomi Left"
    xmp:
      address: 0x170F443E
      command: 0x1A002300
    on_press:
      then:
        - remote_transmitter.transmit_raw:
            carrier_frequency: 36kHz
            code: [1000,-580,580,-1160,580,-580,580,-870,580,-1160,580,-580,580,-580,580,-1160,580,-1450,580,-870,580,-870,580,-12180]

  - platform: remote_receiver
    name: "XMP Right -> Xiaomi Right"
    xmp:
      address: 0x170F443E
      command: 0x19002400
    on_press:
      then:
        - remote_transmitter.transmit_raw:
            carrier_frequency: 36kHz
            code: [1000,-580,580,-1160,580,-580,580,-870,580,-1160,580,-580,580,-580,580,-1450,580,-580,580,-580,580,-1160,580,-12180]

  - platform: remote_receiver
    name: "XMP Down -> Xiaomi Down"
    xmp:
      address: 0x170F443E
      command: 0x1B002200
    on_press:
      then:
        - remote_transmitter.transmit_raw:
            carrier_frequency: 36kHz
            code: [1000,-580,580,-1160,580,-580,580,-870,580,-1160,580,-580,580,-580,580,-870,580,-1160,580,-1160,580,-580,580,-12180]

  - platform: remote_receiver
    name: "XMP Select -> Xiaomi Ok"
    xmp:
      address: 0x170F443E
      command: 0x18002500
    on_press:
      then:
        - remote_transmitter.transmit_raw:
            carrier_frequency: 36kHz
            code: [1000,-580,580,-1160,580,-580,580,-870,580,-1160,580,-580,580,-580,580,-1450,580,-870,580,-580,580,-1450,580,-12180]

  # - platform: remote_receiver
  #   name: "NEC2 Vol Up -> Xiaomi Vol UP"
  #   nec2:
  #     address: 0x20DF
  #     command: 0x40BF
  #     repeat: false
  #   on_press:
  #     then:
  #       - remote_transmitter.transmit_raw:
  #           carrier_frequency: 36kHz
  #           code: [1000,-580,580,-1160,580,-580,580,-870,580,-1160,580,-580,580,-580,580,-1450,580,-1160,580,-580,580,-580,580,-12180]

  - platform: remote_receiver
    name: "NEC2 Vol Up Repeat -> Xiaomi Vol UP"
    nec2:
      address: 0x20DF
      command: 0x40BF
      repeat: true
    on_press:
      then:
        - remote_transmitter.transmit_raw:
            carrier_frequency: 36kHz
            code: [1000,-580,580,-1160,580,-580,580,-870,580,-1160,580,-580,580,-580,580,-1450,580,-1160,580,-580,580,-580,580,-12180,1000,-580,580,-1160,580,-580,580,-870,580,-1160,580,-580,580,-580,580,-1450,580,-1160,580,-580,580,-580,580,-12180]

  # - platform: remote_receiver
  #   name: "NEC2 Vol Down -> Xiaomi Vol Down"
  #   nec2:
  #     address: 0x20DF
  #     command: 0xC03F
  #     repeat: false
  #   on_press:
  #     then:
  #       - remote_transmitter.transmit_raw:
  #           carrier_frequency: 36kHz
  #           code: [1000,-580,580,-1160,580,-580,580,-870,580,-1160,580,-580,580,-580,580,-1450,580,-1450,580,-580,580,-870,580,-12180]


  - platform: remote_receiver
    name: "NEC2 Vol Down Repeat -> Xiaomi Vol Down"
    nec2:
      address: 0x20DF
      command: 0xC03F
      repeat: true
    on_press:
      then:
        - remote_transmitter.transmit_raw:
            carrier_frequency: 36kHz
            code: [1000,-580,580,-1160,580,-580,580,-870,580,-1160,580,-580,580,-580,580,-1450,580,-1450,580,-580,580,-870,580,-12180,1000,-580,580,-1160,580,-580,580,-870,580,-1160,580,-580,580,-580,580,-1450,580,-1450,580,-580,580,-870,580,-12180]
