esphome:
  platform: ESP8266
  board: esp12e

i2c:
  sda: 4
  scl: 5
  scan: True

packages:
  # buttons: !include buttons.yaml
  display: !include display.yaml
  led: !include led.yaml
  buttons: !include buttons.yaml
  relay: !include relay.yaml
