esphome:
  platform: ESP8266
  board: esp01_1m
  esp8266_restore_from_flash: true

packages:
  core:
    ref: remote-packages
    url: https://github.com/alexyao2015/ESPHomeYAML
    files:
      - yaml/lights/core/core.yaml
  feit:
    ref: remote-packages
    url: https://github.com/alexyao2015/ESPHomeYAML
    files:
      - yaml/lights/feit/lights.yaml
      - yaml/lights/feit/poweron.yaml
