esphome:
  on_boot:
    priority: 399
    then:
      - lambda: |-
          id(boot_count) += 1;
          if (id(boot_count) >= 3) {
            id(emergency_light_enable).execute();
          }
      - delay: 30sec
      - lambda: |-
          id(boot_count) = 0;
globals:
  - id: boot_count
    type: uint8_t
    restore_value: true
    initial_value: '0'
    immediate_sync: true

script:
  - id: emergency_light_enable
    then:
      - light.turn_on:
          id: rgbct_led
          brightness: 100%
          color_temperature: 3500 K
