esphome:
  flash_write_interval: 10s
  esp8266_restore_from_flash: true
  on_boot:
    priority: 399
    then:
      - lambda: |-
          id(boot_count) += 1;
          if (id(boot_count) >= 3) {
            id(emergency_light_enable).execute();
          }
      # Need a delay for globals loop to save before committing
      - delay: 40ms
      - lambda: |-
          global_preferences.sync();
      - delay: 30sec
      - lambda: |-
          id(boot_count) = 0;
globals:
  - id: boot_count
    type: uint8_t
    restore_value: true
    initial_value: '0'

script:
  - id: emergency_light_enable
    then:
      - light.turn_on:
          id: rgbct_led
          brightness: 100%
          color_temperature: 3500 K
