esphome:
  platform: ESP32
  board: node32s

logger:

packages:
  # no onboard led so no need to include led pulsing
  base-core:
    ref: main
    url: https://github.com/alexyao2015/ESPHomeYAML
    files:
      - yaml/core/core.yaml
  generator-monitor:
    ref: main
    url: https://github.com/alexyao2015/ESPHomeYAML
    files:
      - yaml/sensors/generator-monitor/bridge.yaml
      - yaml/sensors/generator-monitor/temp.yaml
