api:
  services:
    - service: start_timer_seconds
      variables:
        timer: int
        relay_run_id: int
      then:
        - lambda: 'id(timer_time) = timer;'
        - lambda: 'id(template_relay_id) = relay_run_id;'
        - script.execute: run_timer_seconds
    - service: start_timer_minutes
      variables:
        timer: int
        relay_run_id: int
      then:
        - lambda: 'id(timer_time) = timer*60;'
        - lambda: 'id(template_relay_id) = relay_run_id;'
        - script.execute: run_timer_seconds
    - service: start_timer_hours
      variables:
        timer: int
        relay_run_id: int
      then:
        - lambda: 'id(timer_time) = timer*60*60;'
        - lambda: 'id(template_relay_id) = relay_run_id;'
        - script.execute: run_timer_seconds
    - service: cancel_timer
      then:
        - lambda: 'id(timer_time) = 0;'
        - lambda: 'id(template_relay_id) = 0;'
