external_components:
  - source:
      type: git
      url: https://github.com/oxan/esphome-stream-server
      ref: master
    components: [stream_server]

uart:
  id: uart_bus
  rx_pin: GPIO4
  tx_pin: GPIO2
  baud_rate: 115200 # 9600
  debug:
    direction: BOTH
    after:
      timeout: 100ms
    sequence:
      - lambda: UARTDebug::log_hex(direction, bytes, ' ');
      - if:
          condition:
            lambda: "return (direction == uart::UART_DIRECTION_RX);"
          then:
            - script.execute: pulse_zigbee_led_tx
          else:
            - script.execute: pulse_zigbee_led_rx

stream_server:
  uart_id: uart_bus
  port: 6638

binary_sensor:
  - platform: stream_server
    connected:
      name: "Serial Connected"

script:
  - id: pulse_zigbee_led_tx
    mode: queued
    max_runs: 2
    then:
      - light.turn_on:
          id: led_1
          brightness: 100%
          transition_length: 0ms
      - delay: 50ms
      - light.turn_off:
          id: led_1
          transition_length: 0ms

  - id: pulse_zigbee_led_rx
    mode: queued
    max_runs: 2
    then:
      - light.turn_on:
          id: led_2
          brightness: 100%
          transition_length: 0ms
      - delay: 50ms
      - light.turn_off:
          id: led_2
          transition_length: 0ms
