external_components:
  - source:
      type: git
      url: https://github.com/oxan/esphome-stream-server
      ref: master
    components: [stream_server]

uart:
  id: uart_bus
  rx_pin: GPIO4
  tx_pin: GPIO2
  baud_rate: 115200 # 9600
  debug:
    direction: BOTH
    after:
      timeout: 100ms
    sequence:
      - lambda: UARTDebug::log_hex(direction, bytes, ' ');
      - script.execute: pulse_zigbee_led

stream_server:
  uart_id: uart_bus
  port: 6638

binary_sensor:
  - platform: stream_server
    connected:
      name: "Serial Connected"
      on_press:
        then:
          - light.turn_on:
              id: led_1
              brightness: 100%
              transition_length: 0ms
      on_release:
        then:
          - light.turn_off:
              id: led_1
              transition_length: 0ms

script:
  - id: pulse_zigbee_led
    mode: queued
    max_runs: 2
    then:
      - light.turn_on:
          id: led_2
          brightness: 100%
          transition_length: 0ms
      - delay: 50ms
      - light.turn_off:
          id: led_2
          transition_length: 0ms
