esp32:
  board: esp-wrover-kit
  framework:
    type: esp-idf

esphome:
  name: ${name}
  comment: ${device_description}
  on_boot:
    priority: 600
    then:
      - switch.turn_off: download_mode
      - switch.turn_on: zigbee_reset

packages:
  # no onboard led so no need to include led pulsing
  core:
    ref: main
    url: https://github.com/alexyao2015/ESPHomeYAML
    files:
      # core
      - yaml/core-wired/core.yaml
      # zigbee bridge
      - yaml/sensors/zigbee/bridge.yaml
      - yaml/sensors/zigbee/ethernet.yaml
      - yaml/sensors/zigbee/i2c.yaml
      - yaml/sensors/zigbee/switches.yaml
