esp32:
  board: esp-wrover-kit

esphome:
  on_boot:
    priority: 600
    then:
      - button.press: zigbee_reset

packages:
  # no onboard led so no need to include led pulsing
  core:
    ref: main
    url: https://github.com/alexyao2015/ESPHomeYAML
    files:
      # core
      - yaml/core-wired/core.yaml
      # zigbee bridge
      - yaml/sensors/zigbee/bridge.yaml
      - yaml/sensors/zigbee/buttons.yaml
      - yaml/sensors/zigbee/ethernet.yaml
      - yaml/sensors/zigbee/i2c.yaml
