sensor:
  - platform: hlw8012
    change_mode_every: 3
    update_interval: 3s
    sel_pin:
      number: GPIO12
      inverted: true
    cf_pin: GPIO5
    cf1_pin: GPIO14
    current_resistor: 0.001
    voltage_divider: 940
    current:
      name: "${real_devicename} Current"
      unit_of_measurement: A
      filters:
        # https://esphome.io/components/sensor/index.html#calibrate-linear
        - calibrate_linear:
          # - 0.0000 -> 0.0110 # Relay off no load
          # - 0.0097 -> 0.0260 # Relay on no load
          - 0.9270 -> 0.7570
          - 2.0133 -> 1.6330
          - 2.9307 -> 2.3750
          - 5.4848 -> 4.4210
          - 8.4308 -> 6.8330
          - 9.9171 -> 7.9830
        # Normalize for plug load
        # - lambda: if (x < 0.0260) return 0; else return (x - 0.0260);
    voltage:
      name: "${real_devicename} Voltage"
      unit_of_measurement: V
      filters:
        - calibrate_linear:
          - 109.5769 -> 110.7000
          - 111.1019 -> 112.2000
          - 112.7357 -> 113.9000
          - 114.4785 -> 115.3000
          - 114.7508 -> 115.9000
          - 115.1320 -> 116.0000
          - 118.2908 -> 117.0000
          - 119.2711 -> 117.0000
    power:
      name: "${real_devicename} Power"
      id: wattage
      unit_of_measurement: W
      filters:
        - calibrate_linear:
          # - 0.0000 -> 0.5900 # Relay off no load
          # - 0.0000 -> 1.5600 # Relay on no load
          - 198.5129 -> 87.8300
          - 434.2469 -> 189.5000
          - 628.6241 -> 273.9000
          - 1067.0067 -> 460.1000
          - 1619.8098 -> 699.2000
          - 2043.0282 -> 885.0000
        # Normalize for plug load
        # - lambda: if (x < 1.5600) return 0; else return (x - 1.5600);

  # https://esphome.io/components/sensor/total_daily_energy.html
  - platform: total_daily_energy
    name: "${real_devicename} Total Daily Energy"
    power_id: wattage
    filters:
      - multiply: 0.001
    unit_of_measurement: kWh
