globals:
  - id: total_meter_pulses
    type: int
    restore_value: false
    initial_value: "0"

sensor:
  - platform: pulse_meter
    pin:
      number: GPIO13
      inverted: true
      mode:
        input: true
        pullup: true
    internal_filter: 50ms
    internal_filter_mode: PULSE
    name: 'RO Water Meter Flow Rate'
    unit_of_measurement: "gallons/min"
    filters:
      - multiply: 0.1
    on_value:
      then:
       - lambda: |-
          id(total_meter_pulses) += 1;
  - platform: template
    unit_of_measurement: 'Gallons'
    name: 'RO Water Meter Total'
    lambda: |-
      return id(total_meter_pulses) / 10.0;
button:
  - platform: template
    name: "Reset RO Water Meter Total"
    on_press:
      - lambda: |-
          id(total_meter_pulses) = 0;
